//Taylor Zweigle, 2024
export const GET_EVENTS = "GET_EVENTS";
export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const GET_SELECTED_DATE = "GET_SELECTED_DATE";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

export const GET_SELECTED_START_TIME = "GET_SELECTED_START_TIME";
export const SET_SELECTED_START_TIME = "SET_SELECTED_START_TIME";

export const GET_SELECTED_VIEW = "GET_SELECTED_VIEW";
export const SET_SELECTED_VIEW = "SET_SELECTED_VIEW";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
