//Taylor Zweigle, 2024
export const GET_EVENTS = "GET_EVENTS";
export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const GET_TODOS = "GET_TODOS";
export const CREATE_TODO = "CREATE_TODO";
export const DELETE_TODO = "DELETE_TODO";

export const GET_SELECTED_DATE = "GET_SELECTED_DATE";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";

export const GET_SELECTED_START_TIME = "GET_SELECTED_START_TIME";
export const SET_SELECTED_START_TIME = "SET_SELECTED_START_TIME";

export const GET_SELECTED_THEME = "GET_SELECTED_THEME";
export const SET_SELECTED_THEME = "SET_SELECTED_THEME";

export const PARTIAL_DAY = "PARTIAL_DAY";
export const MULTIPLE_DAYS = "MULTIPLE_DAYS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
